#!/bin/bash
#arvu kontroll - positiivne voi negatiivne
#
echo -n "Sisesta arv: "
read arv
#nuud kontrollime kas arv on positiivne
if [ $arv -gt 0 ]
then
   #jah, arv on suurem kui 0 - positiivne
   echo "$arv on positiivne"
#kui ei ole suurem kui 0 - negatiivne
else
   echo "$arv on negatiivne"
#if lause tuleb korralikult lõpetada
fi

