#!/bin/bash
#
#kolmnurk
#
#ülemine pool
echo -n "Sisesta ridade arv: "
read ridade_arv
for((r=1; r<$(($ridade_arv)); r++))
do
   #veerud - tärnid
   for((t=1; t<$r; t++))
   do
     echo -n "* "
   done

  for((t=1; t<$(($ridade_arv - $r + 1)); t++))
  do
    echo -n "o "
  done
  echo #reavahetus
done
