#!/bin/bash
#
# tärniruut
#
# tekitame read
for((r=1; r<5; r++))
do
  #kontrollime kui r on 1
  if [ $r -eq 1 -o $r -eq 4 ]; then
  #joonistame tärnid
    for((v=1; v<6; v++))
    do
      echo -n "* "
      done
    else
    #tärn
    echo -n "* "
    for((v=2; v<5; v++))
    do
      echo -n "  "
    done
    echo -n "* "
   fi
  #kõik vahepealsed read
  echo
done
