#!/bin/bash
#
#kolmnurk
#
#ülemine pool
echo -n "Sisesta ridade arv: "
read ridade_arv
for((r=$ridade_arv; r>0; r--))
do
   #veerud - tärnid
   for((t=1; t<$r; t++))
   do
     echo -n "o "
   done

  for((t=1; t<$(($ridade_arv - $r + 2)); t++))
  do
    echo -n "* "
  done
  echo #reavahetus
done
