#!/bin/bash
#
# ip järgi arvuti kontrollimine
algus=0
lopp=0

echo -n "Sisesta algus: "
read algus
echo -n "Sisesta lopp: "
read lopp

echo -n > ping_tulemus
#sisestame alguse ja lõpu
for ((nr=$algus; nr<=$lopp; nr++))
#for ip in 172.23.13.{$algus..$lopp}
do
    ip=172.23.13.$nr
    #teostame antud ip pingi
    ping -c 1 $ip > /dev/null #väljundid on kustutatud
    #kontrollime ping käsu tulemust, kas läks läbi
    if [ $? -eq 0 ]; then
    #kui $? on 0 - korras
    echo "$ip - ok" >> ping_tulemus
  else
    echo "$ip - not ok" >> ping_tulemus
  fi #skripti lõpp
done
