#!/bin/bash
#Vastavalt kellaajale tervitab

echo -n "Sisesta tund: " #küsib kasutajalt aja väärtust
read number

if [ $number -ge 6 -a $number -le 12 ]; then #proovib läbi vastavalt tingimustele
    echo "Tere hommikust"
elif [ $number -ge 13 -a $number -le 18 ]; then
    echo "Tere päevast"
elif [ $number -ge 18 -a $number -le 22 ]; then
    echo "Tere õhtust"
elif [ $number -ge 22 -a $number -le 24 ] || [ $number -ge 0 -a $number -le 6 ]; then
    echo "Head ööd"
else
    echo "Ebasobilik number"
fi

#skripti lõpp
